#!/usr/bin/env python3
import argparse
import importlib.util
import pathlib
import sys
from typing import Any


ROOT = pathlib.Path(__file__).resolve().parents[1]
MATRIX_PATH = ROOT / "config" / "feature-matrix.tsv"
SUITE_ROOT = ROOT / ".logs" / "hardware-smoke-suite"
REMAINING_GATES_ROOT = ROOT / ".logs" / "remaining-gates-preflight"


def load_script(module_name: str, script_name: str) -> Any:
    path = ROOT / "scripts" / script_name
    spec = importlib.util.spec_from_file_location(module_name, path)
    if not spec or not spec.loader:
        raise SystemExit(f"Cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def rel(path: str | pathlib.Path) -> str:
    try:
        return str(pathlib.Path(path).resolve().relative_to(ROOT))
    except (OSError, ValueError):
        return str(path)


def build_records(matrix_path: pathlib.Path, suite_root: pathlib.Path, remaining_root: pathlib.Path) -> list[dict[str, Any]]:
    goal = load_script("goal_completion_audit", "goal-completion-audit.py")
    visual = load_script("visual_evidence_audit", "visual-evidence-audit.py")

    rows = goal.load_matrix(matrix_path)
    goal_records = goal.audit_rows(
        rows,
        goal.load_suite_results(suite_root),
        goal.load_remaining_gate_results(remaining_root),
    )
    visual_records = {item["id"]: item for item in visual.audit_rows(rows)}

    records: list[dict[str, Any]] = []
    for item in goal_records:
        visual_item = visual_records.get(item["id"], {})
        records.append(
            {
                **item,
                "visual_status": visual_item.get("visual_status", "unknown"),
                "visual_artifacts": visual_item.get("artifacts", []),
                "visual_gap": visual_item.get("visual_gap", ""),
            }
        )
    return records


def render_markdown(records: list[dict[str, Any]]) -> str:
    complete = sum(1 for item in records if item["complete"])
    camera_verified = sum(1 for item in records if str(item["visual_status"]).startswith("camera-verified"))
    remaining_gated = sum(1 for item in records if not item["complete"])
    lines = [
        "# Evidence Index",
        "",
        "Generated by `scripts/evidence-index.py --markdown`.",
        "",
        "This is a cross-reference map for the board verification work. It combines the strict goal-completion audit, latest hardware-smoke-suite summary, visual OCR evidence, feature docs, and remaining-gate preflight status. It is not a replacement for the underlying audits.",
        "",
        f"Summary: `{complete}` of `{len(records)}` feature directions are complete under `make goal-completion-audit`; `{camera_verified}` reference camera/OCR evidence; `{remaining_gated}` still need external, manual, conditional, or quiet-window evidence.",
        "",
        "Related generated reports:",
        "",
        "- `docs/goal-completion-audit.md`",
        "- `docs/hardware-evidence-audit.md`",
        "- `docs/visual-evidence-audit.md`",
        "- `docs/remaining-gates-preflight.md`",
        "- `docs/remaining-gates-supervised-runbook.md`",
        "",
        "| ID | Priority | Completion | Doc evidence | Suite | Visual | Remaining gate | Next action |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    details: list[str] = []
    for item in records:
        suite = item["suite_status"]
        if item["suite_summary"]:
            suite = f"{suite} `{item['suite_summary']}`"
        remaining = "-"
        if item["remaining_gate_status"]:
            remaining = item["remaining_gate_status"]
            if item["remaining_gate_scope"]:
                remaining = f"{remaining} `{item['remaining_gate_scope']}`"
            if item["remaining_gate_summary"]:
                remaining = f"{remaining} `{item['remaining_gate_summary']}`"
        lines.append(
            "| {id} | {priority} | {completion} | {doc_items} item(s) `{doc}` | {suite} | {visual} | {remaining} | {next_action} |".format(
                id=item["id"],
                priority=item["priority"],
                completion=item["completion"],
                doc_items=item["doc_items"],
                doc=item["doc"],
                suite=suite,
                visual=item["visual_status"],
                remaining=remaining,
                next_action=item["next_action"],
            )
        )
        details.extend(["", f"## {item['id']}", ""])
        details.append(f"- Feature doc: `{item['doc']}`")
        details.append(f"- Completion: `{item['completion']}`")
        details.append(f"- Hardware suite: {suite}")
        details.append(f"- Visual status: `{item['visual_status']}`")
        if item["visual_artifacts"]:
            details.append("- Visual artifacts:")
            details.extend(f"  - `{path}`" for path in item["visual_artifacts"])
        else:
            details.append(f"- Visual gap: {item['visual_gap']}")
        if item["remaining_gate_status"]:
            details.append(f"- Remaining gate: {remaining}")
        details.append(f"- Next action: {item['next_action']}")
    lines.extend(details)
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a consolidated evidence index across board verification audits.")
    parser.add_argument("--matrix", default=str(MATRIX_PATH))
    parser.add_argument("--suite-root", default=str(SUITE_ROOT))
    parser.add_argument("--remaining-gates-root", default=str(REMAINING_GATES_ROOT))
    parser.add_argument("--markdown", action="store_true")
    args = parser.parse_args()

    records = build_records(
        pathlib.Path(args.matrix),
        pathlib.Path(args.suite_root),
        pathlib.Path(args.remaining_gates_root),
    )
    if args.markdown:
        print(render_markdown(records), end="")
        return 0

    complete = sum(1 for item in records if item["complete"])
    camera_verified = sum(1 for item in records if str(item["visual_status"]).startswith("camera-verified"))
    incomplete = len(records) - complete
    print(
        "evidence_index_summary "
        f"features={len(records)} complete={complete} incomplete={incomplete} camera_verified={camera_verified}"
    )
    for item in records:
        print(
            "evidence_index "
            f"id={item['id']} completion={item['completion']} suite={item['suite_status']} "
            f"visual={item['visual_status']} remaining_gate={item['remaining_gate_status'] or 'none'}"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
